import React, { useEffect, useRef, useState } from "react";

export default function CheerleadingVideoPreviewPage({ shared }) {
  const request = shared.authedApiRequest || shared.apiRequest;
  const videoRef = useRef(null); const shellRef = useRef(null);
  const [videos, setVideos] = useState([]); const [active, setActive] = useState(null); const [url, setUrl] = useState("");
  const [playing, setPlaying] = useState(false); const [progress, setProgress] = useState(0); const [duration, setDuration] = useState(0); const [tick, setTick] = useState(Date.now()); const [error, setError] = useState("");
  useEffect(() => { request({ action: "getCheerleadingVideoPreview" }).then(({ result }) => { if (!result?.ok) throw new Error(result?.error || "無權限"); setVideos(result.data?.videos || []); }).catch((e) => setError(e.message)); }, []);
  useEffect(() => { const id = window.setInterval(() => setTick(Date.now()), 15000); return () => window.clearInterval(id); }, []);
  const open = async (video) => { try { const { result } = await request({ action: "getCheerleadingVideoPreviewPlayback", data: { videoId: video.id } }); if (!result?.ok) throw new Error(result?.error || "播放失敗"); setActive(video); setUrl(result.data.url); setPlaying(false); } catch (e) { setError(e.message); } };
  const toggle = async () => { const v = videoRef.current; if (!v) return; if (v.paused) { await v.play(); setPlaying(true); } else { v.pause(); setPlaying(false); } };
  const fullscreen = () => { const shell = shellRef.current; if (shell?.requestFullscreen) shell.requestFullscreen(); };
  const format = (s) => `${Math.floor((s || 0) / 60)}:${String(Math.floor((s || 0) % 60)).padStart(2, "0")}`;
  return <><style>{`.cheer-video-shell:fullscreen,.cheer-video-shell:-webkit-full-screen{width:100vw;height:100dvh;border-radius:0}.cheer-video-shell:fullscreen video,.cheer-video-shell:-webkit-full-screen video{width:100%;height:100%;object-fit:contain}`}</style><main className="min-h-screen bg-slate-950 px-4 py-6 text-white"><div className="mx-auto max-w-5xl space-y-5"><h1 className="text-2xl font-bold">啦啦隊影片 · 自製播放器預覽</h1><p className="text-sm text-slate-400">僅 Linus 測試；全螢幕仍保留浮水印。</p>{error ? <p className="rounded-xl bg-rose-950 p-3 text-rose-200">{error}</p> : null}<div className="flex flex-wrap gap-2">{videos.map((v) => <button key={v.id} onClick={() => open(v)} className="rounded-full bg-slate-800 px-4 py-2 text-sm hover:bg-pink-600">{v.title}</button>)}</div>{url ? <div ref={shellRef} className="cheer-video-shell relative overflow-hidden rounded-2xl bg-black"><video ref={videoRef} src={url} playsInline onTimeUpdate={(e) => setProgress(e.currentTarget.currentTime)} onLoadedMetadata={(e) => setDuration(e.currentTarget.duration)} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} className="w-full" /><div className={`pointer-events-none absolute z-10 rounded bg-black/45 px-2 py-1 text-xs font-semibold ${["left-3 top-3", "right-3 top-3", "bottom-16 left-3", "bottom-16 right-3"][Math.floor(tick / 15000) % 4]}`}>Linus Tseng · {new Date(tick).toLocaleString("zh-TW", { hour12: false })}</div><div className="absolute bottom-0 left-0 right-0 flex items-center gap-3 bg-black/75 p-3"><button onClick={toggle} className="rounded bg-white px-3 py-1 text-sm font-bold text-black">{playing ? "暫停" : "播放"}</button><input type="range" min="0" max={duration || 0} value={progress} onChange={(e) => { const v = videoRef.current; if (v) v.currentTime = Number(e.target.value); setProgress(Number(e.target.value)); }} className="flex-1" /><span className="text-xs">{format(progress)} / {format(duration)}</span><button onClick={fullscreen} className="rounded border border-white/60 px-3 py-1 text-sm">全螢幕</button></div></div> : null}</div></main></>;
}
